### ISSUE TITLE
Run unittests during build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qimage2ndarray-feedstock#2]
Tried to do this before, but ran into issues as it was unable to import some modules that were included with the tests. Seems only to happen during conda builds and was not unique to this package. Will need to investigate why this happens and come up with a fix.

**Comment by pelson** [comment]
There is an interesting balance to be found when running tests. We don't really want to run the full test suite of a package (one assumes that was done when the package was released), but we do want to make sure that we have built the package correctly. The easiest way is most certainly to run the whole test suite, but sometimes that is just overkill. I'll leave it to you to find the sweet spot on this one. :+1:

**Comment by jakirkham** [comment]
You're, of course, right. My feeling is if it compiles source code, we should try to run the tests. If it is pure Python and they are doing CI, there is no point in bothering. In this case, the tests are quite fast so the build time penalty is negligible.

**Comment by hmeine** [comment]
I have an idea why this maybe happens: Does conda run the tests *before* the installation?  I think the tests just `import qimage2ndarray`, which only works if the package is in the path.

**Comment by jakirkham** [comment]
IIRC this was after install. Basically this issue ( https://github.com/hmeine/qimage2ndarray/issues/9 ) that we were discussing yesterday.

**Comment by jakirkham** [comment]
Going to go ahead and close this for now. `qimage2ndarray` is not compiling anything and we do have import tests. If there is demand for running the test suite, we can always re-evaluate later.
