### ISSUE TITLE
Is there support for PySide2?

### ISSUE THREAD

**Issue by AndiLi99** [conda-forge/qimage2ndarray-feedstock#23]
The commit history seems to suggest support for PySide2. 
https://github.com/hmeine/qimage2ndarray/issues/12

**Comment by jakirkham** [comment]
Ultimately this is an upstream question. That said, it does appear they added support in 1.7, which is in the process of being released. HTH

**Comment by hmeine** [comment]
I released 1.7 yesterday, which – to the best of my knowledge, I could not test it myself – supports PySide2.
