### ISSUE TITLE
Building sip components

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qimage2ndarray-feedstock#3]
Carried over from [here]( https://github.com/conda-forge/staged-recipes/pull/107#issuecomment-197928969 ).

In `qimage2ndarray`, there is a [`setup_sip.py`]( https://github.com/hmeine/qimage2ndarray/blob/master/setup_sip.py ) and [a sip file]( https://github.com/hmeine/qimage2ndarray/blob/master/qimageview.sip ). We are not building these currently and it doesn't look like they have been touched recently. Should we building them, are they needed/used, or can/should we keep the current `setup.py` build?

cc @hmeine

**Comment by hmeine** [comment]
Correct.  Recent versions of PyQt make the extension unnecessary.  I am keeping it for PythonQt (yet another wrapper), but I could probably remove the sip stuff.  (I think I kept it for older sip versions.)
Therefore, this issue can be closed.

**Comment by jakirkham** [comment]
Great. Thanks for clarifying. Closing.

If this changes in the future for other bindings like PythonQt, feel free to ping me here or open a new issue and we can sort it out at that time.
