### ISSUE TITLE
Handling Python Qt bindings

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qimage2ndarray-feedstock#4]
Carried over from [here](https://github.com/conda-forge/staged-recipes/pull/107#issuecomment-197928969).

This can use PyQt4, PyQt5, or PySide. There should be some way of exposing this to the user. One strategy for handling common APIs like this in conda is [`features`](http://conda.pydata.org/docs/building/meta-yaml.html#id1). This allows one to select any common API for building and allow one to pick the right variant at install time. I don't believe Python Qt bindings are tracked at present. This probably worth of discussion. @ccordoba12, how do you guys handle this issue with Spyder?

cc @hmeine

**Comment by jakirkham** [comment]
Given that `qimage2ndarray` handles loading Python Qt bindings by searching for what modules may already have been imported, maybe it makes sense to not explicitly depend on any Python Qt bindings at all. This would likely be the easiest fix. Thoughts @stuarteberg?

**Comment by stuarteberg** [comment]
I guess you're right.  I know the upcoming version of conda can support optional dependencies.  Maybe both PySide and Qt4 and Qt5 can all be listed as optional?  Not sure what benefit that would bring beyond just not requiring any at all.  Presumably if a package requires `qimage2ndarray`, it already requires `qt` or `pyside`, and thus requirements in this package would be redundant.

**Comment by hmeine** [comment]
That would also match how I handled it in setup.py…

**Comment by jakirkham** [comment]
Optional dependencies as they exist in `conda`/`conda-build` now are more for handling cases where you want to guarantee a version constraint is met when the dependency ends up being installed (even though it is not explicitly required). Not sure that is needed for this case, but I could be wrong.

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/qimage2ndarray-feedstock/pull/21 ).
